plugins/phrases.py

added help

---

plugins/booru.py

Missing parens

---

plugins/booru.py

More abstraction

---

commands.py

cleaned up a bit, should respond to failed commands with the stack trace

Better error handling

---

plugins/photos.py

Takes an image url, returns a url of the hugeified image

backend for a waifu2x command

---

plugins/games.py

Better output, cleaner parsing, !r as alias, repeat last roll

Roll improvements

---

plugins/uwu.py

Pwease accept my puww wequest

---

plugins/booru.py

changed addsecret to return a tuple of (filename, password) so that commands can store the password for later verification

Addsecret returns password

---

plugins/booru.py

Also an attempt at better y-spacing for !doge

Advanced antitrash for gelbooru

---

plugins/booru.py

rule34 now works correctly
getResponse no longer directly modifies the list of tags received

fixed rule34, improved getResponse

---

plugins/booru.py

I have no way to test this locally but it looks close enough

Filter NFSW content in SFW chats

---

plugins/booru.py

SFW filter fix

---

plugins/audiophrases.py

Tabs instead of line breaks because the list is getting out of control

Fewer line breaks in listsounds

---

plugins/token.py

This code is top secret so just accept this pull request without looking at it

Cryptographically Secure LocusToken command

---

plugins/games.py

Discord API renamed "server" to "guild" just to spite us

Fixed !ship

---

plugins/phrases.py

Also fixed repeated function name

Added !IAA

---

plugins/booru.py

Random range calculation was off by one

Fixed index out of bounds when return_tags=True

---

plugins/audiophrases.py

Should make it so that if someone presses the stop button, the sound will actually stop. Also makes it so that sound doesn't loop unless someone presses the "repeat" emoji. Pressing it again toggles looping off.

Fix looping

---

plugins/gpt.py

In order for  this to work you will need to `pip install nomic`.
It will download the model itself very very slowly, so instead you should
1.  [Download the model via torrent](https://tinyurl.com/gpt4all-lora-quantized)
2. Place the file in ~/.nomic
3. Chmod it to something cool and fun like 777
I haven't really tested this beyond an REPL proof-of-concept but I did squint at the code for a few seconds once I finished writing it so I think its perfect.
THIS PULL REQUEST IS PROVIDED BY ME “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ME BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT …

Prototype gpt4all plugin

---

plugins/admin.py

I forgor .replace isn't in place

fix fixtwit

---

plugins/admin.py

Only fixtwit tweets ("statuses") and remove chaff

fixtwit fixes
